/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_rust_cross_jni_RustCrossJni */

#ifndef _Included_com_example_rust_cross_jni_RustCrossJni
#define _Included_com_example_rust_cross_jni_RustCrossJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_rust_cross_jni_RustCrossJni
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_rust_1cross_1jni_RustCrossJni_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_rust_cross_jni_RustCrossJni
 * Method:    gen_quaternion_str
 * Signature: (FFFF)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_rust_1cross_1jni_RustCrossJni_gen_1quaternion_1str
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
